import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document, Types } from "mongoose";

export type HabitSuggestionDocument = HabitSuggestion & Document;

@Schema({ timestamps: true })
export class HabitSuggestion {
    @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
    userId: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'User' })
    suggestedBy?: Types.ObjectId; // Admin/Coach who suggested or AI

    @Prop({ type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending', index: true })
    status: string;

    @Prop({ required: true })
    name: string;

    @Prop({ enum: ['BOOLEAN', 'NUMERIC'], default: 'BOOLEAN' })
    type: 'BOOLEAN' | 'NUMERIC';

    @Prop()
    targetValue?: number;

    @Prop()
    unit?: string;

    @Prop()
    description?: string;

    @Prop()
    reason?: string; // Why AI/Admin suggested this habit

    @Prop()
    category?: string; // e.g., 'fitness', 'nutrition', 'sleep', 'mindfulness'

    @Prop()
    aiGenerated: boolean; // true if generated by AI, false if manually created by admin

    @Prop({ type: Date })
    approvedAt?: Date;

    @Prop({ type: Date })
    rejectedAt?: Date;

    @Prop({ type: Types.ObjectId, ref: 'User' })
    approvedBy?: Types.ObjectId;

    @Prop()
    rejectionReason?: string;

    @Prop()
    adminNotes?: string;
}

export const HabitSuggestionSchema = SchemaFactory.createForClass(HabitSuggestion);
